# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "HHU SLAM LAB"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://slam.phil.hhu.de/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "All content rights reserved &copy; {year} HHU SLaM Lab"

############################
## Advanced options below ##
############################


# Get last modified date for content from Git?
enableGitInfo = false


# Plausible analytics



# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687
summaryLength = 30

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true 
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]
  fractions = false

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.

[menu]
  [[menu.main]]
    identifier = "theLab"
    name = "The Lab"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/#news"
    parent = "theLab"
    weight = 2
  [[menu.main]]
    identifier = "theTeam"
    name = "The Team"
    url = "/#people"
    parent = "theLab"
    weight = 2
  [[menu.main]]
    identifier = "thephysicallab"
    name = "The Physical Lab"
    url = "/#lab"
    parent = "theLab"
    weight = 3
  [[menu.main]]
    identifier = "joining"
    name = "Joining"
    url = "/#joining"
    parent = "theLab"
    weight = 4
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/"
    weight = 2
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/#publications"
    parent = "research"
    weight = 1
  [[menu.main]]
    identifier = "grantsAndProjects"
    name = "Grants and Projects"
    url = "/#projects"
    parent = "research"
    weight = 2
  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/"
    weight = 3
  [[menu.main]]
    identifier = "seminars"
    name = "Seminars"
    url = "/#teaching"
    parent = "teaching"
    weight = 1
  [[menu.main]]
    identifier = "tutorials"
    name = "Tutorials"
    url = "https://docs.slam.phil.hhu.de"
    parent = "teaching"
    weight = 2
  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "https://slam.phil.hhu.de/events"
    weight = 4
